package com.training.boot.jpa.repository;

import java.util.List;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.query.Param;

import com.training.boot.jpa.entities.EmployeeEntity;

// Implementation of this interface is done by spring data jpa
public interface EmployeeRepository extends CrudRepository<EmployeeEntity, Long> {
	  // save
	// Optional<> findById
	// findAll
	// count()
	// deleteById()
	
	// Queries will be generated by JPA Query builder
	// select e from EmployeeEntity e where e.email = "email";
	public EmployeeEntity findByEmail(String email);
	
	// select e from EmployeeEntity e where e.age = ?1
	// ?1 -> age
	//public  List<EmployeeEntity> findByAge(int age);
	
	// select e from EmployeeEntity e where e.email=?1 && e.lastname= ?2
	// ?1 -> email ?2 -> lastname
	// Based on more than one property
	public  EmployeeEntity findByEmailAndLastName(String email, String lastname);
	
	
	// manual query - for entity class
	@Query("SELECT  e FROM EmployeeEntity e where e.age =  :age")
	public  List<EmployeeEntity> findByAge(@Param("age") int age);
	
	
	
	
}

